
#Balance Settings
[balance]
	#How much forge energy per tick should each connection allow before upgrades?
	#Keep in mind that multiple tiny pipes can be connected to each block (up to 64), and pipes have unlimited throughput.
	#Full sized pipes can be upgrades up to 32x this base speed (by default).
	#(default: 256 fe/tick)
	#Range: > 1
	fe_per_tick = 256
	#How many millibuckets of fluid per second should each connection allow before upgrades? (1000mB = 1 bucket)
	#Keep in mind that multiple tiny pipes can be connected to each block (up to 64), and pipes have unlimited throughput.
	#Full sized pipes can be upgrades up to 32x this base speed (by default).
	#(default: 500mB per second, which is about 25mB per tick)
	#Range: > 4
	mb_per_second = 500
	#How many items per second can each connection transfer before upgrade?
	#Keep in mind that multiple tiny pipes can be connected to each block (up to 64), and pipes have unlimited throughput.
	#Full sized pipes can be upgrades up to 32x this base speed (by default).
	#Also, items move through pipes instantaneously.
	#For context, vanilla hoppers transfer 2.5 items per second.
	#(default: 2 items/second)
	#Range: 1 ~ 64
	items_per_second = 2
	#How much should each speed upgrade multiply the throughput?
	#Speed upgrade multipliers are cumulative. So, if a speed upgrade multiplies by 2, 2 upgrades multiply by 4,
	#3 multiply by 8, etc.
	#(default: 2.0 times)
	#Range: 1.25 ~ 16.0
	speed_upgrade_multiplier = 2.0
	#How many speed upgrades can be applied to a single pipe?
	#(default: 5 )
	#Range: 1 ~ 64
	speed_upgrade_max = 5

