
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1003522
	#The name of the modpack
	modpackName = "SCSP-20LT - Low Tech"
	#The version of the modpack
	modpackVersion = "3.0.0-1.20.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

