
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1033141
	#The name of the modpack
	modpackName = "SCSP-20KS - the Kitchen Sink"
	#The version of the modpack
	modpackVersion = "2.3.2.1-1.20.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

