
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 938896
	#The name of the modpack
	modpackName = "SCSP-LP20 - Lets Play MC20"
	#The version of the modpack
	modpackVersion = "5.3.0-1.20.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

