
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1011022
	#The name of the modpack
	modpackName = "SCSP-20CA - Creative Adventure"
	#The version of the modpack
	modpackVersion = "2.0.0-1.20.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

